---
- name: start an instance with a public IP address
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create EC2
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        # key_name: "po's-key"
        vpc_subnet_id: subnet-0d8aa66b
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        network:
          assign_public_ip: true
        image_id: ami-007855ac798b5175e
        state: stopped
        tags:
          Environment: Testing









